### ISSUE TITLE
Add support for type parameters in annotations

### ISSUE THREAD

**Issue by pgrandjean** [milessabin/shapeless#1051]
Follow up on issue #922 and pull request #925. I would like to add support for type parameters in annotations, both variable and type annotations. For example, define an annotation such as:
```scala
case class MyAnnotation[T](t: T) extends scala.annotation.StaticAnnotation
```

The out type of `Annotations` and `TypeAnnotations` would have the complete "reference" to type `T`.

**Comment by pgrandjean** [comment]
Moreover, what about generalizing Annotations to return all annotations instead of just one annotation type `A`? Example:
```scala
case class HelloWorld(
  name: String @A1[T11, T12, ..., T1n] @A2[T21, T22, ..., T2n], ..., @Am[Tm1, Tm2, ..., Tmn]
)
```

Would be nice to have a single macro to extract in one pass `@A1[T11, T12, ..., T1n] @A2[T21, T22, ..., T2n], ..., @Am[Tm1, Tm2, ..., Tmn]`, no?

**Comment by alexarchambault** [comment]
AFAIC, I think it would be nice to have.

**Comment by pgrandjean** [comment]
I have a working prototype. Will try to submit a PR in the coming days.

**Comment by pgrandjean** [comment]
@joroKr21 just wondering, is this going to work with Scala 3?

**Comment by joroKr21** [comment]
> @joroKr21 just wondering, is this going to work with Scala 3?

The Scala 3 story is a bit messy for shapeless because it uses a lot of macros.

This particular implementation won't work on Scala 3.
There is Shapeless 3 which works only with Scala 3 on the [shapeless-3 branch](https://github.com/milessabin/shapeless/tree/shapeless-3).
I don't know much about it yet, so I can't say what it offers in terms of annotations.
Separately from that we have an issue to port shapeless 2 in some form to Scala 3: #1043
But nobody is working on that at the moment.

**Comment by joroKr21** [comment]
At least there is a step in that direction: #1019
Next would be, write a scalafix rule to replace `Lazy` and `Strict` with by-name implicits in the source code.
