### ISSUE TITLE
Generalize Mapped/Comapped/NatTRel to arbitrary products.

### ISSUE THREAD

**Issue by milessabin** [milessabin/shapeless#124]

**Comment by OlivierBlanvillain** [comment]
Hi Miles! What do you mean by "arbitrary products"? We tried to use `Mapped`/`Comapped` for a `trait Foo[A, B]` with one of the type parameter fixed, but the compiler does not seems to like it. @kanterov did a `Comapped2` to work around the issue (see discussion here https://github.com/adelbertc/frameless/pull/18/files#r55936327), I was wondering if this is what this issue is about.

**Comment by joroKr21** [comment]
Shapeless 3 is here: https://github.com/typelevel/shapeless-3
