### ISSUE TITLE
release for scala-native 0.5

### ISSUE THREAD

**Issue by xuwei-k** [milessabin/shapeless#1355]

**Comment by joroKr21** [comment]
See https://github.com/orgs/typelevel/discussions/135

Also I'm completely out of clue:
https://github.com/milessabin/shapeless/actions/runs/8838312727/job/24528052841
```
[error] Caused by: java.net.ProtocolException: Server redirected too many  times (20)
```

**Comment by milessabin** [comment]
Some discussion here: https://discord.com/channels/632277896739946517/920140670394589224/1235965389024923679

Are we publishing to the wrong sonatype destination somehow?

**Comment by milessabin** [comment]
@joroKr21 I think I've probably resolved the published problem, do you want to give it another try?

**Comment by mpilquist** [comment]
2.4.0-M1 is on Sonatype. Any ETA for 2.4.0 final? Needed for Twiddles which is needed for Skunk.

**Comment by joroKr21** [comment]
2.4.0-M1 is a dud. The only reason to have 2.4.0 would be cross-compiling with Scala 3 but this is hard to achieve.

Regarding releasing for Scala Native 0.5 I'm fine with it. I don't think we should wait for the rest of the typelevel ecosystem because Shapeless is one of the slow-moving projects that is close to the root of the dependency tree.

I think we should do two releases though:
* All changes merged until now
* Bump of Scala Native (and also drop Scala 2.11)

**Comment by milessabin** [comment]
@joroKr21 Agreed with the above.

**Comment by mpilquist** [comment]
Sounds like a plan. Note that most other projects have been first releasing a patch release with all changes to date using 0.4 and then bumping the minor version and releasing against 0.5. Following that model would mean shapeless 2.13.11 against native 0.4 and then same source tree as shapeless 2.14.0 against 0.5.

**Comment by joroKr21** [comment]
https://github.com/milessabin/shapeless/releases/tag/v2.3.12
