### ISSUE TITLE
Injecting values to a Poly defined outside of calling method is awkward

### ISSUE THREAD

**Issue by salanki** [milessabin/shapeless#198]
An easy way to inject information into objects extending Poly is by defining the object inside the method body which is later using the Poly for mapping/folding. In cases where the object is needed for evidence resolution to the method itself things get trickier.

Example:
```scala
case class Something(va: Boolean)
 
object Main extends App {
  import shapeless._
 
  val tc = Something(true)
  val res = Helper.parseCaseClass(tc, false)
 
  println(res) // Should be Something(false)
}
 
object Helper {
  import shapeless._
  import record._
  import poly._
  import syntax.singleton._
 
  object updateElem extends Poly2 {
    import ops.record._
 
    implicit def default[Repr <: HList, T](implicit update: Updater.Aux[Repr, FieldType[T, Boolean], Repr]) =
      at[Repr, T] { (acc, t) => update(acc, field[T](true)) } // I want to replace true here with the `default` argument in the method below
  }
 
  def parseCaseClass[T, Repr <: HList, Kys <: HList](cc: T, default: Boolean)(
    implicit lgen: LabelledGeneric.Aux[T, Repr],
    kysEv: ops.record.Keys.Aux[Repr, Kys],
    folder: ops.hlist.LeftFolder.Aux[Kys, Repr, updateElem.type, Repr]) = {
 
    val rec: Repr = lgen.to(cc)
    val keys: Kys = rec.keys
 
    val res = keys.foldLeft(rec)(updateElem) // How do I inject `default` to the folder, when the folder isn't defined inside this method?
    lgen.from(res)
  }
}
```

In the example above we can't define `updateElem` inside `parseCaseClass` as the type of `updateElem` is needed for the `LeftFolder` evidence. Our only way of injecting `default` into `updateElem` is by defining a custom `LeftFolder` or, easier, injecting it with the initial value.
```scala
 val res = keys.foldLeft((default, rec))(updateElem)._2
```

This isn't a very pretty or flexible solution.

**Comment by milessabin** [comment]
Some bad news, some good news ...

The bad news is that there's nothing that we can do to directly solve this problem in general ... a satisfying solution of the form you want would require forms of dependent typing that go beyond Scala's current capabilities.

The good news is that while looking at this again I've come up with a somewhat more attractive solution for this specific case and sufficiently similar ones. The aim is to have the fold parametrized by a boolean value, and we can capture that by having the fold yield a function of the form `Boolean => Repr` instead of a value of type `Repr`.

This gives us something along the following lines,

```scala
object Helper {
  import shapeless._
  import labelled._
  import record._
  import poly._
  import syntax.singleton._

  object updateElem extends Poly2 {
    import ops.record._

    implicit def default[Repr <: HList, T](implicit update: Updater.Aux[Repr, FieldType[T, Boolean], Repr]) =
      at[Boolean => Repr, T] { (acc, t) => (b: Boolean) => update(acc(b), field[T](b)) }
  }

  def parseCaseClass[T, Repr <: HList, Kys <: HList](cc: T, default: Boolean)(
    implicit lgen: LabelledGeneric.Aux[T, Repr],
    kysEv: ops.record.Keys.Aux[Repr, Kys],
    folder: ops.hlist.LeftFolder.Aux[Kys, Boolean => Repr, updateElem.type, Boolean => Repr]) = {

    val rec: Repr = lgen.to(cc)
    val keys: Kys = rec.keys

    val resFn: Boolean => Repr = keys.foldLeft((_: Boolean) => rec)(updateElem)
    val res = resFn(default)
    lgen.from(res)
  }
}

case class Something(va: Boolean)

object Main extends App {
  import shapeless._

  val tc = Something(true)
  val res = Helper.parseCaseClass(tc, false)

  println(res) // Something(false)
}
```

Which is fairly close to your original.

I'm going to close this ticket now, because I don't think we're going to be able to do significantly better than this. If anyone _is_ able to come up with a better solution, please let me know.
