### ISSUE TITLE
Unable to reference type class instance inside of class definition after migrating to 2.1

### ISSUE THREAD

**Issue by sgrif** [milessabin/shapeless#346]
I've been experimenting with using type classes from shapeless to remove some boilerplate from the Android framework. The use case here is rather interesting, however, as what I ultimately need is for the class to implement a java interface. While I can move the bulk of the behavior into the type class, I still need the adapter layer that ensures the class being serialized implements this interface. To make things even more difficult, the interface defines an abstract static member, so there's no way to achieve this with standard Scala inheritance.

Right now my solution has been to define a trait which can be used to define most of the methods required by the interface. However, I still need access to the `Parceler` instance, which appears to only be possible with an abstract member. (See https://github.com/sgrif/scala-android-parceling/blob/124f5b23bcfebf15319c1d0f201f3cdc1d03ff3d/src/main/scala/Parceled.scala) You can see example usage on 2.0 here: https://github.com/sgrif/scala-android-parceling/blob/124f5b23bcfebf15319c1d0f201f3cdc1d03ff3d/src/test/scala/ParceledTest.scala#L49-L66

After migrating to 2.1, I am no longer able to get the implicit instance of `Parceler[Foo]` inside of the definition of the `Foo` class.

**Comment by milessabin** [comment]
Is this resolved via the fix for #345?

**Comment by sgrif** [comment]
No, this one doesn't even compile. It's a separate issue. While there is technically an explicit type annotation, I'm not sure how I could remove it, since the only time it's explicitly referenced is as an abstract method.

This is what the relevant code isolated looks like, along with the compiler errors I get for various ways I attempted to define the member.

```scala
trait Parceled[T] { self: T =>
  def parceler: Parceler[T]
}

case class Foo(x: Int, y: String) extends Parceler[T] {
  val parceler = implicitly[Parceler[Foo]] // could not find implicit value for parameter e: androidParceling.Parceler[androidParceling.test.ParceledTest.Foo]

  val parceler = Parceler[Foo] // could not find implicit value for parameter ct: shapeless.Lazy[androidParceling.Parceler[androidParceling.test.ParceledTest.Foo]]
}
```

**Comment by sgrif** [comment]
Also just worth noting the class `Foo` in the files I'm mentioning here is a different class from the test files in the other issue.

**Comment by sgrif** [comment]
Interestingly, this one works:

```scala
class Foo extends Parceled[T] {
  val parceler: Parceler[Foo] = Parceler[Foo]
}
```

**Comment by sgrif** [comment]
I see a similar issue if I try to use an auto derived instance for a collection class, such as `List`.

**Comment by milessabin** [comment]
Can you put together a self-contained example that I can play around with?

**Comment by milessabin** [comment]
```scala
val parceler: Parceler[Foo] = Parceler[Foo]`
```
Is fine because the val isn't implicit.

**Comment by sgrif** [comment]
https://gist.github.com/sgrif/2f2bc5b8aae7063cc2f4

**Comment by milessabin** [comment]
Thanks for the example.

The requirement for the type annotation [here](https://gist.github.com/sgrif/2f2bc5b8aae7063cc2f4#file-example-scala-L51),

```scala
val parceler: Parceler[Foo] = Parceler[Foo]
```
Is due to the fact that if no type annotation is provided then the type of `parceler` must be inferred from the RHS of the definition, `Parceler[Foo]`, but this depends on the type of `Foo` being fully know, which in turn depends on knowing the type of `parceler`. So the root cause of the error is actually a cycle ... it's unfortunate that the error message isn't very helpful here.

The reason that the unannotated version worked with shapeless 2.0.0 is that previously it would not have considered vals defined in the body of the case class to be relevant to the result type of `Parceler[Foo]`. The change in 2.1.0 is "as designed" (it supports the widened applicability of `Generic` to some non-case classes), but this is a slightly unexpected consequence, so I'll give it some more thought. I'm not going to change the behaviour for 2.2.0 however, since adding the type annotation is the right thing to do in any case.

I'm not clear whether the definition of `val parceller` in the body of the case class is just illustrative or reflects your actual design ... being defined as a case class member means that a new instance of `Parceler[Foo]` will be created for each nee `Foo` instance. I would expect to see a definition of this sort on the companion object of `Foo` ... in which case see my comment on #345 wrt _not_ providing a type annotation on the val definition if it is implicit.

Apropos of `Parceler[List[A]]`, this isn't being derived because `List[A]` isn't a product type. If you want an instance to be derived for lists you need to implement `TypeClass{Companion}` rather than `ProductTypeClass{Companion}`. Alternatively you can stick with products and provide a hand-written instance for `List[A]` along the following lines,

```scala
implicit def listParceler[T](implicit pt: Parceler[T]): Parceler[List[T]] = new Parceler[List[T]] {
  def read(parcel: Parcel): List[T] = ... read list using Parceler for T ...
  def write(parcel: Parcel, value: List[T]): Unit = ... write list using Parceler for T ...
}
```

**Comment by sgrif** [comment]
> I'm not clear whether the definition of val parceller in the body of the case class is just illustrative or reflects your actual design

You are correct, it should probably be defined on the companion object, and be `implicitly[Parceler[Foo]]` there. 

> Apropos of Parceler[List[A]], this isn't being derived because List[A] isn't a product type.

Does being a product type mean something other than inheriting from `scala.Product`? Because `List` does.

**Comment by milessabin** [comment]
Yes it does.

Product types are concrete instantiatable types with value members. They're represented generically as `HLists` (effectively nested pairs).

Things like `List[T]` are represented generically as `Coproducts` (effectively nested `Either`s) ... specifically `Nil.type :+: ::[T] :+: CNil` which is roughly the same as `Either[Nil.type, Either[::[T], Nothing]]`.

**Comment by sgrif** [comment]
Thank you for the thorough explanation on all fronts. It looks like this is user error on my part in all cases, then. I appreciate you taking the time to help me understand this.
