### ISSUE TITLE
Generic too broad in 2.2?

### ISSUE THREAD

**Issue by alexarchambault** [milessabin/shapeless#360]
Compared to 2.1, it handles the following new cases (possibly others?),
```scala
class C

Generic[C]
Generic[Array[String]] // This one in particular looks surprising
```

**Comment by alexarchambault** [comment]
(Quickly asked you about it on gitter, better to discuss it here.)

**Comment by milessabin** [comment]
`class C` is intended ... it's as case-class-like as `case class C()`.

`Generic[Array[...]]`, on the other hand, isn't intended and the current behaviour (yielding `HNil` as the representation type) is definitely a bug.

**Comment by alexarchambault** [comment]
About `class C`, I understand it is intended, but... I find it still somewhat surprising in practice.

Most of the time, I would consider this kind of classes as blackboxes, that I wouldn't want to assimilate to a case class when deriving type classes (codecs, pretty-printers, ...). I'd prefer to see type class derivation just fail for them (and possibly allow their derivation explicitly via a non implicit method).

I may end up enforcing automatic type class derivation for generic products to apply only for real `Product`s. For example,
```scala
implicit def instanceEncodeJson[F, G](implicit
  gen: LabelledGeneric.Aux[F, G],
  encode: Lazy[EncodeJson[G]]
): EncodeJson[F] = ...
```
would become
```scala
implicit def productInstanceEncodeJson[F <: Product, G](implicit // type constraint on F
  gen: LabelledGeneric.Aux[F, G],
  ev: HasProductGeneric[F],
  encode: Lazy[EncodeJson[G]]
): EncodeJson[F] = ...

implicit def coproductInstanceEncodeJson[F, G](implicit
  gen: LabelledGeneric.Aux[F, G],
  ev: HasCoproductGeneric[F],
  encode: Lazy[EncodeJson[G]]
): EncodeJson[F] = ...
```

**Comment by milessabin** [comment]
FWIW I made this change to support @cvogt's Scalacheck examples ... if we revert the new behaviour then they'll no longer work as expected.

**Comment by milessabin** [comment]
> Most of the time, I would consider this kind of classes as blackboxes, that I wouldn't
> want to assimilate to a case class when deriving type classes (codecs, pretty-printers, ...).
> I'd prefer to see type class derivation just fail for them (and possibly allow their derivation
> explicitly via a non implicit method).

Can you flesh out this argument a little ... what motivates that preference?

One of the things that this supports is, eg. non-case classes with lazy members ... needed for immutable cyclic structures ... do you really want to exclude them?

I guess what I really need is some fairly precise criteria for deciding whether a given type should have a generic representation or not. case classes only is too narrow IMO, you think the current implementation is too broad. How do we mark out the space in between?

**Comment by alexarchambault** [comment]
Looking more closely at https://github.com/alexarchambault/scalacheck-shapeless/blob/master/src/test/scala/org/scalacheck/Definitions.scala#L55-L56, I didn't know at the time whether they should be considered case class-like those of https://github.com/milessabin/shapeless/blob/master/core/src/test/scala/shapeless/generic.scala#L96-L109. If this use case was the only motivation, they definitely shouldn't imo.

If you think it's ok to just revert that (I don't know the consequences for non case classes), let's just do that.

The fear I was having was type classes being automatically derived too broadly and unexpectedly. I ran into that in scalacheck-shapeless recently (https://github.com/alexarchambault/scalacheck-shapeless/blob/master/src/main/scala/org/scalacheck/Shapeless.scala#L100, `List[T]` was considered a coproduct instead of a collection), and I fear there may be others in scalacheck-shapeless/argonaut-shapeless. (I'm going to add more tests to check that.)

About the examples of the issue, I just ran into them when trying to quickly address https://github.com/lihaoyi/Ammonite/issues/47 with shapeless. But the more strict behaviour of `Generic` in 2.1 should be ok (haven't tested yet though).

**Comment by milessabin** [comment]
`List[T]` being considered a coproduct is absolutely by design. I'm not going to revert that. Can you explain what the problem is here?

**Comment by milessabin** [comment]
I think your problem with the `Shrink` instance is actually a issue with implicit prioritization for orphan type class instances in general. The generic instance is accessible without a prefix so it overrides the instance available in the implicit scope.

This is a problem (I'm trying to deal with it in shapeless-contrib at the moment), but the problem emphatically isn't the fact that `List[T]` can be viewed as a coproduct.

**Comment by alexarchambault** [comment]
I agree with List[T] being a coproduct

**Comment by alexarchambault** [comment]
I used List just to illustrate sometimes surprising (but perfectly legit in this case) type class derivation. But it's less legit for Array[T], and possibly the classes of scalacheck-shapeless you were talking about.

**Comment by milessabin** [comment]
The reason that @cvogts `Bar` didn't have a `Generic` instance is that it had no constructor arguments: I previously had a check for at least one val constructor argument ... adding a single constructor val argument would have made it case-class-like and it would have had a `Generic` instance. I decided that there wasn't a difference between 0 and 1 arg that was sufficient to motivate the exclusion of the former, so I removed the check.

`Baz` was excluded on two counts. First that it had multiple argument lists and second that it had non-val constructor arguments. The latter is well motivated (we need the constructor arguments to be accessible from constructed values, which is only possible if they're vals). The former isn't really, but since we probably do want to exclude case classes with multiple argument lists and that multiple argument lists are rare in non-case classes, I thought it wouldn't be too much of a loss to exclude this case as well.

**Comment by milessabin** [comment]
I completely agree that `Array[T]` is a problem.

We want `gen.from(gen.to(x)) == x` but that's not something that we can guarantee in general, even for case classes. I went to some lengths to ensure that, eg. `String` didn't end up with a `Generic` representation, and I thought that would cover all but edge cases which could be worked around in a reasonably straightforward way. `Array[T]` is obviously not an edge case, so that needs fixing.

**Comment by milessabin** [comment]
Hmm ... though now I come to think of it, maybe `String` _does_ have a generic representation: `HList` ... which could then be refined via `Typeable`. And `"foo".type` could be represented as `'f'.type :: 'o'.type :: 'o'.type :: HNil`. And I guess `Array[T]` could be handled similarly.

The issue is that we don't want strings and arrays to be represented as `HNil` (which is want would drop out of the current implementation by default unless blocked) because that's not information preserving (hence we don't get `gen.from(gen.to(x)) == x`).

**Comment by alexarchambault** [comment]
For arrays, I agree that the problem lies more in the generic representation being `HNil` rather in having a `Generic` instance per se. But what generic representation would you give to arrays then?

**Comment by milessabin** [comment]
That is wandering off topic for this ticket a little ... maybe on gitter?

**Comment by alexarchambault** [comment]
Sure!

**Comment by cvogt** [comment]
I agree with case class being too narrow and classes being too broad. Conceptually you want type classes to be derivable when the classes satisfy certain laws, right? We expect case classes to satisfy certain laws (even though some can be broken), but other classes may satisfy some laws as well. Maybe declaring which laws they satisfy would help, maybe again via type classes.

**Comment by alexarchambault** [comment]
I was thinking of an opt-in mechanism, like an additional import, to allow some non-case classes to be seen case classes.

**Comment by cvogt** [comment]
The "opt-in" mechanism could be a type-class that automatically whitelists certain sorts
 of classes, i.e. single constructor argument list only vals ones. An alternative non-implicit import could allow selective whitelisting of classes instead.
