### ISSUE TITLE
Witness suport for all singleton types in Scala

### ISSUE THREAD

**Issue by Tzbob** [milessabin/shapeless#376]
At the moment the following scenarios should work:

```scala
  val wTrue = Witness(true)
  val w0 = Witness(0)
  val wFoo = Witness('foo)
  val wBaz = Witness("baz")

  object Quux
  val wQuux = Witness(Quux)
```

While stable identifiers that are a subclass of AnyRef do not when they could:

```scala
  val baaz = new Object {}
  val wBaaz = Witness(baaz) // Witness of baaz.type
```

**Comment by milessabin** [comment]
Thanks for you help in tracking this one down :-)

Fixed for 2.11.x in https://github.com/milessabin/shapeless/commit/93fe82e550414bd8470915a79936b05da6ab0e00.

The fix for 2.10.x in https://github.com/milessabin/shapeless/commit/1552f983a1aac0f81e85733910ae024771d2125f is only partial due to what appears to be a bug in 2.10.x relating to local class definitions ... given that a manually written instance (see `NestingBug`) compiles incorrectly there doesn't seem to be a lot we can do in the macro. Hopefully enough of the use cases (eg. things along the lines of `convert` and `boundedConvert`) are covered that this will not prove to be a serious issue in practice.

**Comment by Tzbob** [comment]
Thank you for solving it :+1: 

I'm comparing my own fix to this one and I'm noticing that there isn't an explicit check that the stable identifiers are subtypes of AnyRef:

```scala
  class ValueTest(val x: Int) extends AnyVal

  object PathDependentSingleton2 {
    val x = new ValueTest(5)
    val wX = Witness(x)
    type XT = wX.T
  }
```

This compiles just fine but I have no idea what ```XT``` is supposed to be here. ```x.type``` is an invalid expression since ```x``` is not subclassing ```AnyRef``` so I'm not sure if this behavior is intended? 

If it is then Shapeless Witness macros add support for singleton types on value classes by treating them as reference types which may lead to un{expected, documented} behavior? An example that could possibly confuse people:

```scala
    val x = new ValueTest(5)
    val y = new ValueTest(5)
    val wX = Witness(x)
    val wY = Witness(y)
    implicitly[wX.T =:= wY.T]
```

**Comment by milessabin** [comment]
Good catch. Would you mind opening a ticket for this. I don't think it's a showstopper for 2.2.0 though, so I'll schedule it for 2.3.0.

**Comment by Tzbob** [comment]
Done: https://github.com/milessabin/shapeless/issues/379
