### ISSUE TITLE
cachedImplicit does not work when used in companion

### ISSUE THREAD

**Issue by mpilquist** [milessabin/shapeless#508]
Consider the following:
```scala
scala> :paste
import shapeless.cachedImplicit

trait Foo[A]
object Foo {
  implicit def materialize[A]: Foo[A] = new Foo[A] {}
}

case class Bar(x: Int)
object Bar {
  implicit val foo: Foo[Bar] = cachedImplicit
}

Bar.foo
// Exiting paste mode, now interpreting.

import shapeless.cachedImplicit
defined trait Foo
defined object Foo
defined class Bar
defined object Bar
res0: Foo[Bar] = null
```
If instead of defining `Bar.foo` as a val, we define it as a def, we get a stack overflow exception.

This occurs because the implementation of `cachedImplicit` attempts to hide the implicit definition by shadowing it's name, however, because the definition is in the `Bar` companion, scalac finds the definition when searching the companion.

**Comment by notxcain** [comment]
This one is a duplicate of #390

**Comment by milessabin** [comment]
Oh, interesting! Yes ... the problem in that case was obscured for my by the issue with the refinements. If you don't mind I'll close that one in favour of this, because the example here is clearer (for me, anyhow).

**Comment by milessabin** [comment]
I've just been looking at this now. There doesn't seem to be any way of preventing lookup in `Bar`'s implicit scope analogous to the use of shadowing to frustrate direct lookup.

However, I think we can get the desired effect by importing the materializer in the body of `object Bar` or it's enclosing scope. ie.,

```scala
import shapeless.cachedImplicit

trait Foo[A]
object Foo {
  implicit def materialize[A]: Foo[A] = new Foo[A] {}
}

case class Bar(x: Int)
object Bar {
  import Foo._
  implicit val foo: Foo[Bar] = cachedImplicit
}

Bar.foo
```

Note that this isn't quite the same as invoking `Foo.materialize[Bar]` directly, because in practice `materialize` would be a macro method and can only be invoked in the presence of,

```scala
import scala.language.experimental.macros
```

Is that good enough? Or does it still imply too much coupling between `object Bar` and `object Foo`?

**Comment by milessabin** [comment]
@mpilquist @notxcain See also: https://github.com/milessabin/shapeless/issues/390#issuecomment-170224924.

**Comment by clhodapp** [comment]
See https://github.com/milessabin/shapeless/pull/527

**Comment by milessabin** [comment]
This should now work as expected ... many thanks to @clhodapp for pointing in the right direction :-)
