### ISSUE TITLE
Compilation-order-dependent failure when deriving typeclass instance for recursive type

### ISSUE THREAD

**Issue by m50d** [milessabin/shapeless#555]
Smallish example (confirmed with 2.11.7):

````scala
//A.scala
import shapeless.LabelledTypeClassCompanion

sealed trait MyNat
case class MyZero() extends MyNat
case class MySucc(x: MyNat) extends MyNat

trait MyTypeClass[F]
object MyTypeClass extends LabelledTypeClassCompanion[MyTypeClass] {
  override val typeClass = ???
}
````

````scala
//B.scala
object Derive {
  MyTypeClass[MyNat]
}
````

````
C:\Users\Michael\workspace\paperdoll\src\main\scala>scalac -cp shapeless_2.11-2.3.0.jar A.scala B.scala

C:\Users\Michael\workspace\paperdoll\src\main\scala>scalac -cp shapeless_2.11-2.3.0.jar B.scala A.scala
B.scala:2: error: could not find Lazy implicit value of type MyTypeClass[MyNat]
  MyTypeClass[MyNat]
             ^
one error found
````

From a different error I sometimes saw with the larger example where I first encountered this problem I *suspect* this may be an issue with ownership of symbols generated by the `Lazy` macro.

**Comment by milessabin** [comment]
This is a manifestation of [SI-7046](https://issues.scala-lang.org/browse/SI-7046?jql=text%20~%20%22knowndirectsubclasses%22). You need to ensure that your ADT has been typechecked before you attempt to materialize a `Generic` instance for the root trait.

This is a general problem with the `knownDirectSubclasses` macro call: I'm afraid there's nothing we can do here ... it has to be fixed in the compiler.
