### ISSUE TITLE
Shapeless version 2.1 is missing on Sonatype

### ISSUE THREAD

**Issue by muuki88** [milessabin/shapeless#578]
Hi,

It seems the version `2.1` for scala `2.10` is missing on sonatype:

https://oss.sonatype.org/index.html#nexus-search;gav~com.chuusai~shapeless_2.10~~~~kw,versionexpand

Can you confirm this?

cheers,
Muki

**Comment by milessabin** [comment]
Prior to 2.2.0 shapeless was built with a full cross version for Scala 2.10.x because early releases in the 2.10.x series had bugs in the implementation of implicit macros which couldn't be worked around.

You will find builds of 2.1.0 for a subset of 2.10.x releases, however I strongly recommend that you upgrade to a more recent shapeless release.

**Comment by muuki88** [comment]
Thanks for the quick reply. We'll try to fix the dependencies that depend on shapeless 2.1.
