### ISSUE TITLE
Type inequality does not work correctly on type parameteres

### ISSUE THREAD

**Issue by tenormadness** [milessabin/shapeless#681]
The following code compiles (and it should not)

    def someMethod[T](in : T) = {
    
      implicitly[T =:!= String]

      // some operation that requires T not String could be called here
      // even though there is no guarantee that this is safe
    }
    val a = someMethod("abc") // here we have just proven String != String

This shows that the technique of shadowing implicits by creating conflicts (used in `=:!=`) is not very safe when erasure occurs. 
I'd be happy to help fix this issue but I'm quite able to come up with a work around. Any suggestion?

**Comment by milessabin** [comment]
I've managed to persuade myself that this isn't a bug. In the case where there's a witness I think the result is uncontroversial,

```scala
def foo[T](in : T)(implicit ev: T =:!= String): Unit = {
  implicitly[T =:!= String]
}
illTyped(""" foo("abc") """)
foo(Nil)
```

Where there's no witness I think the result should be uncontroversial too: here we are observing that within the body of method `bar` the type `T` is not equal to the `String`.
```scala
def bar[T](in : T): Unit = {
  implicitly[T =:!= String]
}
bar("abc")
bar(Nil)
```
And this is surely correct: it it weren't then we ought to be able to invoke `String` methods on `in`. But we can't, and this isn't a surprise. 

Things do get a little more puzzling in this case,

```scala
def baz[T](in : T): Unit = {
  implicitly[T =:!= String]
  foo(in)
}
baz("abc")
baz(Nil)
```
Now it seems that `baz` is able to "forge" a proof that `T` isn't a `String` and propagate it to `foo`. But this isn't what's going on. Whilst the argument to `baz` is known to be a `String` at the call site, that information is lost within the body of `baz`. The existential type of `in` in the body of `baz` is `T` which is not equal to `String` in exactly the same way as in the case of `bar`.

Here's another example which might lend some additional support to the last example. Suppose that instead of losing information about the type of the argument by quantifying we lose information by subtyping,

```scala
def quux(in: AnyRef): Unit = {
  implicitly[in.type =:!= String]
  foo(in)
}
quux("abc")
quux(Nil)
```
In this case I don't think it's any surprise that the type inequality holds without a witness being required, and equally I don't think it's any surprise that the locally synthesized witness be propagatable to `foo`. In this case, as in the last, we haven't "forged" a type inequality, we've changed the static type of the argument (by quantifying in `baz`, by subtyping in `quux`) in such a way that the type inequality must hold ... it's not a forgery, we've made it so.
