### ISSUE TITLE
Unable to derive coproduct when sealed trait and member both have higher-kinded type parameter

### ISSUE THREAD

**Issue by Baccata** [milessabin/shapeless#683]
```scala
type Id[A] = A 

// Error occurs when both the trait and its members are parameterized with a * -> * 

sealed trait Foo[A[_]]
case class Bar[A[_]]() extends Foo[A]

Generic[Bar[Id]] // compiles 
Generic[Foo[Id]] // does not compile

// If the sealed trait is the only one to contain the * -> * , it compiles

sealed trait Pipo[A[_]]
case class Lino() extends Pipo[Id]

Generic[Pipo[Id]] // compiles

```

Using 2.12.1, shapeless 2.3.2

**Comment by milessabin** [comment]
Ahh, I'd missed that the type parameter is semi-phantom in `Bar`. Do you have a compelling example where a `Pipo`/`Lino` style workaround isn't possible?

**Comment by Baccata** [comment]
My bad, I stripped down the constructor parameters to reduce noise, but the bug is still noticeable when the type param is not phantom : 

```
sealed trait Foo[A[_]]
case class Bar[A[_]](x: A[Int], y : A[String]) extends Foo[A]
```

As to why it's important in my use-case, I'm exploring some ideas around fixed-point types with type constraints, and I'd like to construct the coproduct of constraints involved in a given ADT.  So in the example, I'd like to be able to derive an instance for the `Constraints[G[_[_]]] { type Out <: Coproduct}` typeclass where `Constraints[Foo].Out` yields `Int :+: String :+: CNil`

**Comment by teldosas** [comment]
I managed to narrow down the bug to [these lines](https://github.com/milessabin/shapeless/blob/master/core/src/main/scala/shapeless/generic.scala#L418-L421).
```scala
val subst = c.internal.thisType(sym).baseType(baseSym).typeArgs
sym.typeParams.map { param =>
  val paramTpe = param.asType.toType
  baseArgs(subst.indexWhere(_ =:= paramTpe))
}
```
The problem seens to be that 
* `c.internal.thisType(sym).baseType(baseSym).typeArgs` returns a List with elements of type 
`scala.reflect.internal.Types$AbstractNoArgsTypeRef` while 
* `sym.typeParams.map( param => param.asType.toType )` return a List with elements of type `scala.reflect.internal.Types$AbstractArgsTypeRef`

So for our example `subst(0) == A` while `paramTpe == A[_]`. Thus `subst.indexWhere(_ =:= paramTpe)` returns -1 and we get an `IndexOutOfBoundsException`.

This code was added in 1114f09f846b308a368dd6277836860d19425a87

I couldn't understand what is the difference between getting the typeParams with 
* `c.internal.thisType(sym).baseType(baseSym).typeArgs`  and
* `sym.typeParams.map( param => param.asType.toType )` 
Hint? @milessabin 

If we replace `baseArgs(subst.indexWhere(_ =:= paramTpe))` with`baseArgs(subst.indexWhere(_.typeSymbol.asType.toType =:= paramTpe))`

The problem is solved.

**Comment by milessabin** [comment]
The use of `baseType` was at @retronym's suggestion. It appears that the method of asking changes the apparent kind ... I don't know why.

**Comment by retronym** [comment]
Could you explain the intended behaviour of `ctorsOfAux` / `substituteArgs` with an example or two? A few things look odd to me, for instance, it seems to assume that the subclass and base class have the same number of type parameters, and that the subclass extends the parent class with those type parameters directly forwarded to the super type application.

```scala
      val baseArgs = baseTpe.dealias.typeArgs
      val ctorSyms = collectCtors(baseSym).sortBy(_.fullName)
      val ctors =
        ctorSyms flatMap { sym =>
          ...
          def substituteArgs: List[Type] = {
            val subst = c.internal.thisType(sym).baseType(baseSym).typeArgs
            sym.typeParams.map { param =>
              val paramTpe = param.asType.toType
              baseArgs(subst.indexWhere(_ =:= paramTpe))
            }
          }
```

You might be able to solve the problem at hand with:

```scala
              baseArgs(subst.indexWhere(_.typeSymbol == paramTpe.typeSymbol))
```

But without understanding the context, I'm not sure if that will give you false positives.

**Comment by milessabin** [comment]
@retronym thanks, that solves the problem.

This whole area needs a complete rewrite, but to a first approximation what we're trying to do is compute full applied subtypes given a fully applied sealed supertype. Permutation of type arguments between parent and child is allowed, but they must be directly forwarded, and there can be no additional type parameters introduced in the child (because we have no way of instantiating given the information in the supertype).
